### PR TITLE
Update the README to conform to Awesome-List standards

### PR DESCRIPTION
**Pull request by NewAlexandria**
This is a group of changes in response to #40, and fixes things so that [this merge can continue](https://github.com/sindresorhus/awesome/pull/1049). 🎉 

Two links from Vimeo are still failing, [when you lint this through travis.](https://github.com/davidtheclark/remark-lint-no-dead-urls/issues/12#issuecomment-476686770).  It's a known issue, and I think the PR to the master Awesome list would go through, obviously.

### CODE REVIEW

**Comment by NewAlexandria** [comment]
@lvm I [took a few stabs at it](https://github.com/toplap/awesome-livecoding/pull/41/commits/440c9a6687d55cc1bc621169fef4b23eb42f8f9b) on the PR.  You can [see them on my fork, from `afterglow` to `Cyril`](https://github.com/NewAlexandria/awesome-livecoding#languages).

The first one is in the 'new style' with more padding.  All of them after Cyril are the new style, too.

Obviously, none of the new ones lint, but that's not as much the concern at this point, since this is a new awesome-list pattern that was accounted for by the linter.  My main concern is with whether any of these patterns are acceptable to you.   From there, I'll try to sort out what linter changes might best/easiest for a new 'tag style' like this.

```
Ψ awesome-lint
✖ Linting

  README.md:47:41
  ✖  47:41  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  50:43  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  53:31  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  56:72  List item description must end with proper punctuation  remark-lint:awesome/list-item
  ✖  59:1   List item description contains invalid markdown         remark-lint:awesome/list-item

  5 errors
```

Obviously, alternatively, any of these could look well, as we could just call a stalemate on the linting, and all spend extra time outside. ⛰

**Comment by lvm** [comment]
Thanks for this.   
So none of these _styles_ will pass the awesome-lint? (...:grimacing:). Forget about this thing then, sorry to waste your time with this. If you could update the contrib guide to match this new format, that would be awesome (and i will get off your back and merge your changes)

**Comment by NewAlexandria** [comment]
@lvm updated.   Cheers

**Comment by NewAlexandria** [comment]
Thanks.  Is there more you'd like before merging, @lvm ?

**Comment by NewAlexandria** [comment]
body flip ball pass

**Pull request merged**
