### PR TITLE
Add Cane

### PR DESCRIPTION
**Pull request by fennecdjay**
Cane is an interesting MIDI dsl.

### CODE REVIEW

**Review by lvm — CHANGES_REQUESTED** [review]
You seem to be missing the categories (see below other entries).

**Comment by fennecdjay** [comment]
You're right, I'll fix that, sorry for the delay

**Comment by fennecdjay** [comment]
Just added categories

**Review by lvm — APPROVED** [review]

**Comment by lvm** [comment]
Thanks!

**Pull request merged**
