### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tmhglnd**
Added a link to the browser version of Mercury

### CODE REVIEW

**Comment by lvm** [comment]
Hi @tmhglnd what do you think about adding this link to the [libraries and tools](https://github.com/toplap/awesome-livecoding/blob/master/README.md#libraries-and-tools) section instead? 
If I understood correctly, it's the same lang but this new link is a "tool" that uses the lang, is that right?

Thanks

**Comment by tmhglnd** [comment]
Hey, good point. I was not really sure when something in this list should be considered a tool/library or a lang/environment. I thought the Languages are more the stand-alone environments, and the tools/libraries are extensions that can be used within any of those existing languages/environments, but I guess this is not necessarily the case since for example Hydra resides in the libraries/tools.

The web version of Mercury is indeed a "tool" that uses the language, but in that sense I would consider it exactly the same as the MaxMSP version, that is also a tool that uses the mercury language and eventually translates to a max patcher.

In any case I think it is fine to have the web version under tools. In the future I'm actually trying to move from the Max version to have the web version as the "main" version, so by that time I think we might switch.

**Comment by yaxu** [comment]
I think hydra should be under languages rather than tools? In case that helps..

**Comment by lvm** [comment]
It's just a list of links to help people find material. Please, don't over think it.

**Comment by yaxu** [comment]
I think it's OK to discuss this.

I suggest we add Mercury to languages, move Hydra there, and add strudel.tidalcycles.org there too. The list is quite long now though. We could subcategorise into browser-based etc.

**Comment by lvm** [comment]
Yeah, no, that's the thing: I'm not going to discuss it. Don't take this the wrong way but this list has been working just fine with [pretty much the same structure since 2017.](https://github.com/toplap/awesome-livecoding/blob/feffacbf90386ef8a0f62e2a1b3b6594f57acd8f/README.md), don't see why change now.
It's really simple: 
* Is it a language or proposes a "syntax"? goes to the language category. 
* Does it extends a language (or a tool)? goes to the library category. 

Don't see the point on adding subcategories either, that's what tags are for. Again, don't take this the wrong way but adding subcategories leads to more discussion related to "where should i put x", no need for that. 
I mean, what about langs that run on three platforms? should we add them thrice? 

Anyway.

* Is Mercury a language or a library that extends Max/MSP? 
* Is Hydra a language? Or does it extends JS? (I remember vaguely the syntax, but I'm OK with moving it if it's a lang) 
* What does "mercury web" do anyways? Is "Mercury" but for the browser? In that case: Goes to the library category.

**Comment by yaxu** [comment]
Fair enough on avoiding subcategories.

Tidal is a library for Haskell, and doesn't propose a syntax (apart from its mininotation). But it is an embedded domain specific language. As a language, it defines what a computation is for pattern. So I'd keep it in 'language', and move Hydra there for the same reason. Along those lines I'd add Strudel to languages as well.

I don't know too much about Mercury so can't share an opinion on where the different versions should go, it seems a grey area..

**Comment by tmhglnd** [comment]
I agree Hydra should probably be under Language.

Mercury is a domain specific language (has it's own syntax, grammar, parser). It has 2 places where you can use it, the Max version or the Browser version. Both are standalone environments where you code Mercury (and are not required to know Max or JS). I think both could be under language, may I suggest it could look like this:

[Mercury](https://github.com/tmhglnd/mercury) | [Mercury Web](https://mercury.timohoogland.com) - A highly abstracted minimal language for the live coding of algorithmic music designed to make code more accessible for the performer and less obfuscating for the audience.

`Windows | macOS` `Chrome | Firefox` `audio` `visuals` `MaxMSP` `JavaScript`

**Comment by lvm** [comment]
@yaxu Yeah, no question about Tidal (A dsl with a mininotation, being flexible, it proposes a syntax somehow).
+1 to the Hydra recategorization

@tmhglnd Yes! I like a lot your proposal. +1 to that. Also a good solution to future additions.

**Review by lvm — APPROVED** [review]

**Pull request merged**
