### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by fpesari**
Added Algorithmic Music section of the LinuxMusicians forum

### CODE REVIEW

**Comment by kagel** [comment]
Not much discussions there (one topic to be exact). What do you think?

**Comment by lvm** [comment]
Uhm. This would be a -1 for me. The goal for this list is to document good resources, not *every* resource. 
As @kagel points out, there's only one topic going on. Perhaps in the future, if that section is still alive and provides good info, we could add it.

**Comment by fpesari** [comment]
The board was opened two weeks ago...of course there aren't many discussions. The idea is to attract more people, since that forum is very popular among developers of plugins and DAWs and has the potential to bring more people from the FLOSS world into livecoding.

Edit: of course I understand not including it right now. The problem is that it's a "test run" and the board [will close if there is no activity](https://linuxmusicians.com/viewtopic.php?p=127957#p127957)...it's a snake biting its tail. I think advertising it on here, at least for a while, could bring some users there which I believe is a good thing for the livecoding community, because LinuxMusicians is the most active FLOSS audio forum I know.

**Comment by lvm** [comment]
I see, may be trying to advertise it in mailing lists and other forums? there are a couple of places [here](https://github.com/toplap/awesome-livecoding#community).
Creating topics that might encourage people to comment might be a good idea too (So it doesn't looks so empty...)

**Comment by lvm** [comment]
Hi again @fpesari 

Now that a couple of months have gone past, has this subforum got any traction?

**Comment by fpesari** [comment]
> Hi again @fpesari
> 
> Now that a couple of months have gone past, has this subforum got any traction?

Hello @lvm! Sadly not, there is some activity but it has not yet gained that critical mass :disappointed:

**Comment by lvm** [comment]
@fpesari Ok, if you're still interested... fix the conflict and i'll merge the PR.

**Comment by fpesari** [comment]
Done, thanks :smiley:

**Pull request merged**
