### PR TITLE
added Tinalla framework

### PR DESCRIPTION
**Pull request by rexmalebka**
I think this is interesting because there's no approaches on livecoding based on Regex parsing, for the posibility of creating new languages and new forms

### CODE REVIEW

**Comment by bobvanluijt** [comment]
Very cool, like where Tidal is heading 😊👍

**Comment by yaxu** [comment]
This does look awesome! Are there any videos?

**Comment by bobvanluijt** [comment]
Yes: https://tidalcycles.org/index.php/Welcome

**Comment by yaxu** [comment]
Thanks @bobvanluijt, but I meant where Tinalla is heading. I made tidal ;) I think tinalla isn't related to tidal, except it seems to use it's sound engine superdirt.

**Comment by bobvanluijt** [comment]
O haha, sorry, I should have read it better.

What I meant with ”heading” is -for example- the regex parsing. To really go to the _coding_ part of live coding. New ways of expressing music like Tinella, Orca, etc. Are IMHO very interesting.

Keep up the great work mate 😊👍

**Comment by rexmalebka** [comment]
Hello 
sorry, I've been a bit lazy about this project, I  was thiking it could eventually get boring
I made this  
attempt at fitter happier cover
[tinalla + tidalcycles simple attempt](https://youtu.be/tQNOm2WuorM) 

maybe later I'm recording some other usage example

**Pull request merged**
