### PR TITLE
Add Vuo to the "Languages" list

### PR DESCRIPTION
**Pull request by smokris**

### CODE REVIEW

**Comment by lvm** [comment]
Hi there,
I'm not sure about Vuo being _FLOSS_, could you update that part? 

Thanks!

**Comment by smokris** [comment]
Hi, @lvm.  Thanks for your response.  Vuo's source code is available at https://github.com/vuo/vuo, and there's more info about Vuo's open source policy at http://vuo.org/source.  Or if that doesn't meet your requirements, I can remove the `FLOSS` tag.

**Comment by lvm** [comment]
Hi @smokris, sorry! I didn't knew about that, I just did a quick glance at vuo.org :-)

Thanks for your contribution

**Comment by smokris** [comment]
Great.  Thanks, @lvm!

**Comment by lvm** [comment]
no prob

**Pull request merged**
