### PR TITLE
Removed re<urse as it's no longer in development. Added mutate4l whic…

### PR DESCRIPTION
**Pull request by carrierdown**
…h is its successor.

### CODE REVIEW

**Comment by lvm** [comment]
What about adding a mark to denote that's no longer in development instead of removing it? I mean, for historical purposes. This way we can keep track which languages existed over the years.

**Comment by carrierdown** [comment]
Sure, that's okay with me. How should I signify it? Using strikethrough on the whole entry, or just add some sort of label to it like `abandoned`?

**Comment by lvm** [comment]
One one hand, the strikethrough is helpful if you're reading the rendered markdown document.
On the other, the `abandoned` tag is helpful when you're reading the plain-text markdown document.

so, i don't really know. both? 
since it's the first time this happens (i think), it's your choice 😄.

**Comment by carrierdown** [comment]
Nice :) I've added back re<urse with strikethrough and abandoned tag.

**Comment by lvm** [comment]
great! merged!

**Pull request merged**
