### PR TITLE
add wasm-music

### PR DESCRIPTION
**Pull request by petersalomonsen**

### CODE REVIEW

**Comment by yaxu** [comment]
Thanks for the PR! Does WASM allow code editing on-the-fly, without a break in the music? If not then it might be better in a generative music list rather than a live coding list.

**Comment by petersalomonsen** [comment]
It sure does allow code editing on-the-fly without breaking the music. Have a look here: https://youtu.be/-2qqZFrFEf8

**Comment by petersalomonsen** [comment]
and this: https://youtu.be/ZQUo2fZwUgw

or the full playlist of demo videos: https://www.youtube.com/watch?v=ZQUo2fZwUgw&list=PLv5wm4YuO4IxRDu1k8fSBVuUlULA8CRa7&index=3

**Comment by yaxu** [comment]
Great, thanks! Sorry it wasn't immediately clear.

**Pull request merged**
